config/routes.rb
ProjectTracking::Application.routes.draw do
  resources :clients

  resources :projects

  

  root  'static_pages#home'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50}
  validates :country, presence: true



end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client
  default_scope -> { order('deadline_date DESC')}
	validates :name, presence: true, length: { maximum: 50 }
	validates :description, presence: true
	validates :billing_type, presence: true
  validates :budget_amount,numericality: { only_integer: true, greater_than: 0},
              if: :check_billing_type?


                
def check_billing_type?
  billing_type=="fixed"    
end


def self.search(search,status,client)
  if (search || status || client)
   
    find(:all, :conditions => ['name = ? AND status = ? AND client_id = ?',search,status,client])
  else
    find(:all)
  end
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :country)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'will_paginate/array';
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    #@projects_search =  Project.search(params[:name])
    @projects = Project.search(params[:search],params[:status],params[:client_id]).paginate(:page => params[:page],:per_page => 10)

  end

       
  
  # GET /projects/1
  # GET /projects/1.json
  def show
     
    
  end

  # GET /projects/new
  def new
    @project = Project.new

  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        cc = Client.find_by_id(@project.client_id)
        cc.update_attributes(project_id: params[:id])
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :code, :description, :billing_type, :start_date, :deadline_date, :end_date, :github_url, :status,:client_id,:budget_amount)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper




end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
   <%= f.select :country, [ 'India', 'USA','Japan','China','England','Africa']%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table text-align="center" border="1px" cellspacing="10px" cellpadding="10px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.country %></td>
        <td><%= link_to 'Show', client ,class: "btn btn-primary btn-success"%></td>
        <td><%= link_to 'Edit', edit_client_path(client),class: "btn btn-primary btn-sm btn-warning" %></td>
        <td>
         <% if client.projects.any? %>
          <% else %> 
        <%= link_to 'Destroy', client, class: "btn btn-primary btn-sm btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client.country %>
</p>

<div class="span8">
    <% if @client.projects.any? %>
      <h3>Projects (<%= @client.projects.count %>)</h3>
      
      <% @client.projects.each do |f| %>
        <%= f.name %><br/>
      <%end%>

      <% else %>
      No projects 
      
    <% end %>
  </div>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">

    <ul>
     
      <li><%= link_to "Contact Us", contact_path %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Project Tracking", root_path, id: "logo" %>         
        </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTracking</title>
     
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
     <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
  <%= f.label "Billing Type" %> 
  <%= f.select :billing_type,["tnm","fixed"],{},{:class => 'select_option'}  %>
  </div>

  
  <div id="fixed" style="display:none;"> 
    <%= f.label "Enter total Budget Amount" %>    
   <%= f.text_field :budget_amount%>  
  </div>

  
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
    
  </div>
  <div class="field">
    <%= f.label :deadline_date %><br>
    <%= f.date_select :deadline_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :github_url %><br>
    <%= f.text_field :github_url %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, [ 'poc', 'kick off','completed']%>
  </div>
  

<% if params[:action] == 'edit' %>
    <div class="field">
    <%= f.label :client_id %><br>
    <%= f.select("client_id", Client.all.collect {|p| [ p.name, p.id ] },{},:disabled => true)%>
    </div>
<% else %>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.select("client_id", Client.all.collect {|p| [ p.name, p.id ] }) %>
  </div>
<% end %>
   
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>


<script type="text/javascript">
    $(document).ready(function() {
        $( ".select_option" ).change(function() {
            if($(this).val() == 'fixed') {
               $('#fixed').show();
            } else {
              $('#fixed').hide();
              $()
            
            }
        });
        $( ".select_option" ).trigger('change');
        });
</script>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>


<%= form_tag projects_path, :method => 'get' do%>
  <table text-align="center" cellspacing="10px" cellpadding="10px">
  <tr>
    <td>Project Name</td>
    <td>Status</td>
    <td>Client Name</td>
    <td></td>
  
  </tr>
  <tr>
    <td><%= text_field_tag :search, params[:search] %></td>
    <td><%= select_tag(:status,options_for_select(['poc','kick off','completed']))%></td>
    <td><%= select_tag(:client_id,
    options_for_select(Client.all.collect {|p| [ p.name, p.id ]})) %></td>
    <td><%= submit_tag "Search", :name => nil , class: "btn btn-primary btn-info"%></td>
  </tr>
  </table>

<% end%>
  

<table text-align="center" border="1px" cellspacing="10px" cellpadding="10px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Description</th>
      <th>Billing type</th>
      <th>Start date</th>
      <th>Deadline date</th>
      <th>End date</th>
      <th>Github url</th>
      <th>Status</th>
      <th>Clients</th>
      <th></th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.code %></td>
        <td><%= project.description %></td>
        <td><%= project.billing_type %></td>
        <td><%= project.start_date %></td>
        <td><%= project.deadline_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.github_url %></td>
        <td><%= project.status %></td>
        <td><%= Client.find_by_id(project.client_id).name %></td>
        <td><%= link_to 'Show', project ,class: "btn btn-primary btn-success"%></td>
        <td><%= link_to 'Edit', edit_project_path(project) ,class: "btn btn-primary btn-sm btn-warning"%></td>
        <td><%= link_to 'Destroy', project, method: :delete,class: "btn btn-primary btn-sm btn-danger",data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
 
</table>
 <%= will_paginate  %>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path , class: "btn btn-info"%>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @project.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Billing type:</strong>
  <%= @project.billing_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Deadline date:</strong>
  <%= @project.deadline_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>

<p>
  <strong>Github url:</strong>
  <%= @project.github_url %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Client:</strong>
  <%= Client.find_by_id(@project.client_id).name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/static_pages/contact.html.erb
<div class="center hero-unit">
  <h1>Beaver Logic</h1>

  <h2>
   <p>
   	BEAVER LOGIC
	Address: FF – 1,2, JBR Arcade </br>
	Science City Road </br>
	Ahmedabad, Gujarat, India </br> 
	Email: sales@beaverlogic.com </br>
    </p>
  </h2>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Project Tracking</h1>
<table align="center"text-align="center" cellpadding="10" cellpadding="10">
<tr>
<td><%= link_to "List Projects" , 'projects/', class: "btn btn-large btn-info" %></td>
<td> <%= link_to "New Project" , '/projects/new', class: "btn btn-large btn-info" %> </td>

</tr>
<tr>

<td><%= link_to "List Client" , '/clients', class: "btn btn-large btn-info" %> </td>
<td><%= link_to "New Client" , '/clients/new', class: "btn btn-large btn-info" %></td>
</tr>
</table>



</div>